[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python start_services.py"
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
GROQ_API_KEY = ""
MODEL = ""
NEWS_SERVER_URL = "http://localhost:8001/mcp"
STOCK_SERVER_URL = "http://localhost:8002/mcp" 